Light level polling command
dgomes/dali2mqtt pull request #54
Opened 2022-01-09 11:32 UTC by crami

This pull request implements a new command to get brightness and status of lamps and groups.

2022-01-09 12:42 UTC, dgomes reviewed
Wasn't the plan to get the status periodically? that is, without the need for an MQTT command ?

2022-01-09 12:42 UTC, dgomes commented on dali_mqtt_daemon.py
> +        if 'group_' in light:
This block is the same as `on_message_brightness_cmd`

could you please refactor, so we don't repeat this code ?

2022-01-09 12:42 UTC, dgomes commented on dali_mqtt_daemon.py
> +                lamp_state,
Can be made inline:

`MQTT_PAYLOAD_ON if level.value != 0 else MQTT_PAYLOAD_OFF`

2022-01-09 14:23 UTC, dgomes commented on dali_mqtt_daemon.py
> +    return(lamp_object)
```suggestion
    return lamp_object
```

2022-01-10 07:04 UTC, crami commented
I'm quite happy now how this works. Can you please review again.

2022-01-10 08:51 UTC, dgomes requested changes
What about the idea of making this periodic ?

2022-01-10 08:51 UTC, dgomes commented on dali_mqtt_daemon.py
> +        level = None
not required

2022-01-10 08:57 UTC, crami commented on dali_mqtt_daemon.py
> +        level = None
removed that line

2022-01-10 08:59 UTC, crami commented
Will think about making it periodic, still no clue how to get from main to this point. Think it should be a configurable option and this functionality should be in anyway.

2022-01-10 09:00 UTC, merged

2022-01-10 09:00 UTC, dgomes commented
Thank you!